version: "3"

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      TZ: "UTC"
    ports:
      - "5432:5432"

  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "8080:80"
    depends_on:
      - db

  ng:
    container_name: ng
    build: angular
    ports:
      - "80:80"

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "8180:8080"
    volumes:
      - ./config/realm-export.json:/tmp/realm-export.json
    depends_on:
      - db

volumes:
  db-data:
