"""
Django settings for todoproj project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import json
from six.moves.urllib import request
from cryptography.x509 import load_pem_x509_certificate
from cryptography.hazmat.backends import default_backend




# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b+6um8z%n3gznbji6mkww8f9uwn=@-tjr0uw2%tkixl6yg02us'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_jwt',
    'todoapi',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'todoproj.handle_users.EnsureUserExistsMiddleware',
]

ROOT_URLCONF = 'todoproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todoproj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'mypassword',
        'HOST': 'db',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

CORS_ORIGIN_WHITELIST = (
    'http://localhost:4200',
    'http://localhost:8080',
    'http://localhost:8180',
    'http://193.31.26.167:8080',
    'http://193.31.26.167:80',
    'http://193.31.26.167',
    'http://gymtracker.ch',
)



## Add JWT authentication to default authentication classes
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'todoproj.customaut.CustomJSONWebTokenAuthentication',
       #'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
}


KEYCLOAK_CLIENT_PUBLIC_KEY ='-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAucPfvSpsuL5votwsf76TYUrgi7lrYzYnIJAXcYUuDTgeLOyrNzlPKR/VZ7/8O09Q4cO2jHbK5YE+sDj/2J8SLlykqTZl/u+0lRHcA1cjq3Yip4wxFyEJ+IF9F2FgRLEv/ClsQbDnCVu8XEnBZA8N7lJfnji08Ao9bwJu/lY/fOJbUwizPCco2o4O/uF98FxWQ94xM6ZdQJThZ+q7zvyrS3IgBQwrUqrp8biycxouyprj+qUvmafP5L8FYzBhQ0r9ZNWPSHim2fsYa+B5TxDB/FMEMwu20lsYCpok0fmprLBXs/WWesgbpfRa5FGQ+jKcrUDKcwm3glD8NqV/QJ71YwIDAQAB\n-----END PUBLIC KEY-----'

OIDC_HOST = "http://localhost:8180/auth"
# Your OIDC realm
OIDC_REALM = "Project2"
# Additional URL for registration
OIDC_OP_REGISTRATION_ENDPOINT = f"{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/registrations"

OIDC_RP_CLIENT_ID = "myapp"

def jwt_get_username_from_payload_handler(payload):
    return payload.get('preferred_username','user')

JWT_AUTH = {
    'JWT_PAYLOAD_GET_USERNAME_HANDLER': jwt_get_username_from_payload_handler,
    'JWT_PUBLIC_KEY': KEYCLOAK_CLIENT_PUBLIC_KEY,
    'JWT_ALGORITHM': 'RS256',
    'JWT_AUDIENCE': 'account',
    'JWT_ISSUER': 'https://gymtracker.ch/auth/realms/Project2',
    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
} 


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'todoapi' : {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'todoproj': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    }
}
