# Generated by Django 2.2.20 on 2023-11-04 12:01

from django.conf import settings
from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User(pk=2, username="user", is_active=True , email="lorenz@cometoweb.ch")
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_auth0user'),
    ]

    operations = [
    ]
