# Generated by Django 2.2.20 on 2023-11-15 17:37

from django.db import migrations
from django.conf import settings


def create_data(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User(pk=4, username="user2", is_active=True , email="lorenz.gallina@optimatik.ch")
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_exercise_exerciselog_workout_workoutplan'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
