# Generated by Django 2.2.20 on 2024-01-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0006_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='timer_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='timer_active',
            field=models.BooleanField(default=False),
        ),
    ]
